controller_manager: 
  ros__parameters:
    update_rate: 50.0
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50.0
    left_wheel_controller:
      type: effort_controllers/JointVelocityController
      joint: left_wheel_joint
      pid:
        p: 100.0
        i: 0.01
        d: 10.0
    right_wheel_controller:
      type: effort_controllers/JointVelocityController
      joint: right_wheel_joint
      pid:
        p: 100.0
        i: 0.01
        d: 10.0
    cmd_vel_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel: left_wheel_joint
      right_wheel: right_wheel_joint
      wheel_separation: 0.34
      wheel_radius: 0.1
      cmd_vel_timeout: 0.5
      publish_rate: 50.0